package com.thizthizzydizzy.vr_troubleshooting;
import java.io.File;
import java.io.IOException;
public class Main{
    public static File root = new File(new File("src").getAbsoluteFile().getParentFile().getParentFile(), "ThizThizzyDizzy.github.io\\vr-troubleshooting");
    public static void main(String[] args) throws IOException{
        new Page("index", "Troubleshooting Home")
            .paragraph("Welcome to my VR Troubleshooting page! Please pick the type of device you are having issues with:")
            .subpage("VR Headset or Controllers", "(Including built-in extras such as eye tracking or face tracking)", new Page("headset", "VR Headset or Controllers")
                .paragraph("What brand of VR Headset/Controllers are you having trouble with?")
                .subpage("Pimax", null, new Page("pimax", "Pimax Headset/Controllers")
                    .paragraph("Which device are you having trouble with?")
                    .subpage("Pimax Crystal", null, new Page("crystal", "Pimax Crystal"))
                    .subpage("Pimax Crystal Light", null, new Page("crystal-light", "Pimax Crystal Light"))
                    .subpage("Pimax Crystal Controllers", "(the inside-out tracked controllers for the Crystal and Crystal Light)", new Page("crystal-controllers", "Pimax Crystal Controllers"))
                )
                .subpage("Valve", null, new Page("valve", "Valve Headset/Controllers")
                    .paragraph("Which device are you having trouble with?")
                    .subpage("Valve Index Headset", null, new Page("index", "Valve Index"))
                    .subpage("Valve Index Controllers", "(Knuckles)", new Page("knuckles", "Valve Index Controllers"))
                )
            )
            .subpage("Full-body Tracking", "(SteamVR Trackers, IMU tracking, or other types of FBT)", new Page("fbt", "Full-body Tracking")
                .paragraph("What type of Full-body Tracking are you using?")
                .subpage("SteamVR Trackers", "(Usually vive or Tundra trackers)", new Page("steamvr", "SteamVR Trackers")
                    .paragraph("What device are you having trouble with?")
                    .subpage("Vive Tracker", null, new Page("vive", "Vive Trackers"))
                    .subpage("Tundra Tracker", null, new Page("tundra", "Tundra Trackers"))
                )
                .subpage("IMU Trackers", "SlimeVR, HaritoraX, mocopi, etc.", new Page("imu", "IMU Trackers")
                    .paragraph("What device are you having trouble with?")
                    .subpage("SlimeVR Tracker", "(DIY IMU Trackers, or other devices like phones or joycons repurposed as trackers)", new Page("slime", "SlimeVR Trackers"))
                )
            )
            .subpage("Haptics", "(vibration, electrostimulation, or other types of haptic feedback)", new Page("haptics", "VR Haptics")
                .paragraph("What brand of haptics are you using?")
                .subpage("bHaptics", null, new Page("bHaptics", "bHaptics")
                    .paragraph("What device are you having trouble with?")
                    .subpage("Tactal", null, new Page("tactal", "bHaptics Tactal"))
                    .subpage("TactVisor", null, new Page("tactvisor", "bHaptics TactVisor"))
                    .subpage("TactSuit X40", null, new Page("x40", "bHaptics TactSuit X40"))
                    .subpage("TactSuit X16", null, new Page("x16", "bHaptics TactSuit X16"))
                    .subpage("Tactosy for Arms", null, new Page("arms", "bHaptics Tactosy for Arms"))
                    .subpage("Tactosy for Feet", null, new Page("feet", "bHaptics Tactosy for Feet"))
                )
                .subpage("OWO Game", null, new Page("owo", "OWO Haptics")
                    .paragraph("What device are you having trouble with?")
                    .subpage("owoskin", null, new Page("owoskin", "owoskin"))
                )
                .subpage("GiggleTech", null, new Page("giggletech", "GiggleTech Haptics")
                    .paragraph("What device are you having trouble with?")
                    .subpage("Giggle Puck", null, new Page("puck", "Giggle Puck"))
                    .subpage("Giggle Spark", null, new Page("spark", "Giggle Spark"))
                    .subpage("Giggle Bank", null, new Page("bank", "Giggle Bank"))
                )
            )
            .subpage("Other Tracking Accessories", "(Face tracking, eye tracking, hand tracking, etc, DIY or otherwise NOT built into the headset.", new Page("tracking-accessories", "VR Tracking Accessories")
                .paragraph("What type of tracking device are you having trouble with?")
                .subpage("Face Tracking", "(Mouth tracking)", new Page("face", "Face Tracking")
                    .paragraph("What device are you having trouble with?")
                    .subpage("Vive Facial Tracker", "(NOT the Vive Focus 3 facial tracker)", new Page("vive", "Vive Facial Tracker"))
                )
                .subpage("Eye Tracking", "(Including upper face/eybrows)", new Page("eye", "Eye Tracking")
                    .paragraph("What device are you having trouble with?")
                    .subpage("EyeTrackVR", "(DIY Eye trackers)", new Page("etvr", "EyeTrackVR"))
                )
                .subpage("Hand Tracking", null, new Page("hand", "Hand Tracking")
                    .paragraph("What device are you having trouble with?")
                    .subpage("Leap Motion Controller 2", null, new Page("leap-motion-2", "Leap Motion Controller 2"))
                )
            )
            .generate(root);
    }
}
